package test.serviceb.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

@Entity
public class OrderItem {

  /**
   * The unique identifier for the "Item" entity.
   * This field is autogenerated using the IDENTITY strategy.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * Represents the unique identifier of an item.
   * This field maps to the "item" entity and serves as a reference
   * to identify a specific item within the context of an order.
   */
  private int itemId;

  /**
   * Represents the quantity of a specific item in an order.
   * This field stores the numerical value denoting the count of items
   * included for a particular {@link OrderItem} instance.
   */
  private int quantity;

  /**
   * Represents the price of an individual item in an order.
   * This field stores the cost associated with a single unit of the item.
   * The value is stored as a double to account for fractional currency values.
   */
  private double price;

  /**
   * Represents the order associated with a specific {@link OrderItem}.
   * This field establishes a many-to-one relationship between {@link OrderItem} and {@link Orders}.
   * It is mapped to the foreign key column "orderId" in the database and cannot be null.
   */
  @ManyToOne
  @JoinColumn(name = "orderId", nullable = false)
  private Orders order;

  /**
   * Default constructor for the OrderItem class.
   * Initializes an instance of the OrderItem entity with default values for all fields.
   */
  public OrderItem() {
  }

  /**
   * Constructs an instance of the OrderItem class with the specified item ID, quantity, and price.
   *
   * @param itemId   the unique identifier of the item
   * @param quantity the quantity of the item
   * @param price    the price of the item
   */
  public OrderItem(int itemId, int quantity, double price) {
    this.itemId = itemId;
    this.quantity = quantity;
    this.price = price;
  }

  /**
   * Retrieves the unique identifier of this order item.
   *
   * @return the unique identifier as an integer
   */
  public int getId() {
    return id;
  }

  /**
   * Retrieves the unique identifier associated with the item.
   *
   * @return the unique identifier of the item as an integer
   */
  public int getItemId() {
    return itemId;
  }

  /**
   * Sets the identifier for the item associated with this order item.
   *
   * @param itemId the identifier of the item to be set
   */
  public void setItemId(int itemId) {
    this.itemId = itemId;
  }

  /**
   * Retrieves the quantity of the order item.
   *
   * @return the quantity as an integer
   */
  public int getQuantity() {
    return quantity;
  }

  /**
   * Updates the quantity of the order item.
   *
   * @param quantity the new quantity to set for this order item
   */
  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }

  /**
   * Retrieves the price of the order item.
   *
   * @return the price of the order item as a double
   */
  public double getPrice() {
    return price;
  }

  /**
   * Sets the price for this order item.
   *
   * @param price the price to set for the order item
   */
  public void setPrice(double price) {
    this.price = price;
  }

  /**
   * Retrieves the order associated with this order item.
   *
   * @return the associated {@link Orders} instance
   */
  public Orders getOrder() {
    return order;
  }

  /**
   * Sets the order associated with this order item.
   *
   * @param order the {@link Orders} instance to be associated with this order item
   */
  public void setOrder(Orders order) {
    this.order = order;
  }
}
