package test.serviceb.domain;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

@Entity
public class Orders {

  /**
   * The unique identifier for the "Item" entity.
   * This field is autogenerated using the IDENTITY strategy.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  /**
   * Represents the total price of an order.
   * This value is calculated based on the sum of the prices of all items in the order.
   * It is stored as a double to accommodate fractional values.
   */
  private double totalPrice;


  /**
   * Represents the status of an order.
   * The {@code status} field is an instance of the {@link Status} enum,
   * which defines the possible states an order can be in.
   * Possible values include:
   * - {@code CONFIRMED}: Indicates that the order has been confirmed.
   * - {@code SHIPPED}: Indicates that the order has been shipped.
   * - {@code CANCELLED}: Indicates that the order has been cancelled.
   */
  @Enumerated(EnumType.STRING)
  private Status status;

  /**
   * Represents the list of order items associated with an order.
   * Each item in the list corresponds to an instance of the {@link OrderItem} entity.
   * This field is initialized as an empty {@code ArrayList} and can contain multiple {@code OrderItem} objects.
   */
  @JsonManagedReference
  @OneToMany(mappedBy = "order", orphanRemoval = true, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
  private List<OrderItem> orderItems = new ArrayList<>();

  /**
   * Default constructor for the Orders class.
   * Initializes an instance of the Orders entity.
   */
  public Orders() {
  }

  /**
   * Constructs an instance of the Orders class with the specified total price, status, and list of order items.
   *
   * @param totalPrice the total price of the order, represented as a double
   * @param status     the status of the order, represented as an instance of the Status enum
   * @param orderItems the list of items associated with the order, represented as a List of OrderItem objects
   */
  public Orders(double totalPrice, Status status, List<OrderItem> orderItems) {
    this.totalPrice = totalPrice;
    this.status = status;
    this.orderItems = orderItems;
  }

  /**
   * Retrieves the unique identifier of the order.
   *
   * @return the unique identifier of the order as an integer
   */
  public int getId() {
    return id;
  }

  /**
   * Retrieves the total price of the order.
   *
   * @return the total price as a double.
   */
  public double getTotalPrice() {
    return totalPrice;
  }

  /**
   * Sets the total price for the order.
   *
   * @param totalPrice The total price to be set for this order.
   */
  public void setTotalPrice(double totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Retrieves the current status of the order.
   *
   * @return the status of the order as an instance of the {@code Status} enum
   */
  public Status getStatus() {
    return status;
  }

  /**
   * Sets the status of the order.
   *
   * @param status the status to set for the order, represented as an instance of the {@code Status} enum
   */
  public void setStatus(Status status) {
    this.status = status;
  }

  /**
   * Retrieves the list of order items associated with the order.
   *
   * @return a list of {@code OrderItem} objects representing the items in the order
   */
  public List<OrderItem> getOrderItems() {
    return orderItems;
  }

  /**
   * Sets the list of order items for the order.
   *
   * @param orderItems the list of order items to be associated with this order
   */
  public void setOrderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
  }

  /**
   * Adds an order item to the list of items associated with this order.
   * The order item is also linked back to this order.
   *
   * @param orderItem the order item to be added, represented as an instance of the OrderItem class
   */
  public void addOrderItem(OrderItem orderItem) {
    orderItem.setOrder(this);
    this.orderItems.add(orderItem);
  }
}

